# Generated by Django 5.0.7 on 2025-04-03 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professional',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='professional',
            name='subfield',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
