# Generated by Django 5.0.7 on 2025-03-19 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professional',
            name='availability',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='professional',
            name='bio',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='professional',
            name='credentials_file',
            field=models.FileField(blank=True, null=True, upload_to='credentials/'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='professional',
            name='skills',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='professional',
            name='verified_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
