# Generated by Django 5.0.7 on 2025-04-01 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_notification_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='hero_images/'),
        ),
    ]
