# Generated by Django 5.0.7 on 2025-04-03 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20250403_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='externaljob',
            name='apply_url',
            field=models.URLField(blank=True, help_text='Direct link to the external application page, if available.', max_length=500, null=True),
        ),
    ]
