# Generated by Django 5.0.7 on 2025-04-01 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_professional_hero_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional: Image representing this category (e.g., an icon).', null=True, upload_to='category_images/'),
        ),
    ]
