# Generated by Django 5.0.7 on 2025-04-03 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_externaljob_apply_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VerificationToken',
        ),
    ]
