# Generated by Django 5.0.7 on 2025-04-01 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='theme',
        ),
    ]
