# Generated by Django 4.2.27 on 2026-02-02 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_tier_professional_to_plus'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.TextField()),
                ('value_type', models.CharField(choices=[('text', 'Plain Text'), ('html', 'HTML'), ('markdown', 'Markdown')], default='text', max_length=20)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Setting',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['-submitted_at'], 'verbose_name': 'Feedback', 'verbose_name_plural': 'Feedbacks'},
        ),
        migrations.AlterModelOptions(
            name='upgraderequest',
            options={'ordering': ['-requested_at'], 'verbose_name': 'Upgrade Request', 'verbose_name_plural': 'Upgrade Requests'},
        ),
        migrations.AddField(
            model_name='externaljob',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='externaljob',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='externaljob',
            name='provider_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='externaljob',
            name='provider_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='admin_response',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='feedback',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='feedback',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('resolved', 'Resolved')], default='new', max_length=20),
        ),
        migrations.AddField(
            model_name='feedback',
            name='subject',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='feedback',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='message',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='upgraderequest',
            name='lawyer_confirmation_letter',
            field=models.FileField(blank=True, help_text='Letter from a licensed lawyer confirming expertise (required for Premium)', null=True, upload_to='upgrade_documents/'),
        ),
        migrations.AddField(
            model_name='upgraderequest',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='upgraderequest',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='upgraderequest',
            name='payment_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='upgraderequest',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='upgraderequest',
            name='supporting_documents',
            field=models.FileField(blank=True, help_text='Additional supporting documents', null=True, upload_to='upgrade_documents/'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='category',
            field=models.CharField(choices=[('general', 'General Inquiry'), ('support', 'Technical Support'), ('billing', 'Billing & Payments'), ('verification', 'Verification'), ('upgrade', 'Account Upgrade'), ('consultation', 'Consultation Issues'), ('partnership', 'Partnership'), ('other', 'Other')], default='general', max_length=50),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('consultation', 'Consultation'), ('message', 'Message'), ('article', 'Article'), ('research', 'Research'), ('follow', 'Follow'), ('review', 'Review'), ('upgrade', 'Upgrade'), ('verification', 'Verification'), ('job', 'Job'), ('payment', 'Payment'), ('system', 'System')], default='system', max_length=50),
        ),
        migrations.AlterField(
            model_name='upgraderequest',
            name='upgrade_type',
            field=models.CharField(choices=[('plus', 'Plus Tier'), ('premium', 'Premium Tier (Expert)')], max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='tier',
            field=models.CharField(choices=[('basic', 'Basic'), ('plus', 'Plus'), ('premium', 'Premium')], default='basic', max_length=20),
        ),
    ]
