# Generated by Django 4.2.27 on 2026-02-02 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_comments_related_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='allow_instant_messaging',
            field=models.BooleanField(default=True),
        ),
    ]
